In [3]:
import numpy as np

In [3]:
l1=[20,30,40]
l2=[50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [4]:
a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print(a+b)

[20 30 40]
[60 70 80]
[ 80 100 120]


In [5]:
a = np.array([20,30,'60'])
print(a)

['20' '30' '60']


### NUMPY - Creating Arrays , Slicing and Attributes

In [10]:
a = np.array([10,20,30,40])
print(a)
print(type(a))


[10 20 30 40]
<class 'numpy.ndarray'>


In [12]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))
# Multi-diamentional array 

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


### Slicing 

In [15]:
ar1 = np.array([10,20,30,40])
print(ar1)
print(ar1[0])
print(ar1[0:])
print(ar1[1:])
print(ar1[3:])
print(ar1[:])
print(ar1[:3])
print(ar1[:3])

[10 20 30 40]
10
[10 20 30 40]
[20 30 40]
[40]
[10 20 30 40]
[10 20 30]
[10 20 30]


## Attributes

In [18]:
arr2 = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
12
2
int32


## Inspecting of array 

In [47]:
a = [10,20,30,40]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr)) #number of nested values
print(np.size(arr)) # number of element
print(type(arr)) #tyoe of variable
print(arr.dtype) # datatype of array 
print(arr.astype(str)) # conversion of dtype

[10 20 30 40]
(4,)
4
4
<class 'numpy.ndarray'>
int32
['10' '20' '30' '40']


## Mathematical Operation and function of array

In [56]:
arr1 = np.array([60,70,80,90,100])
arr2 = np.array([10,20,30,40,50])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 70  90 110 130 150]
[ 70  90 110 130 150]


In [70]:
arr3 = np.array([[60,70],[80,90]])
arr4 = np.array([[10,20],[30,40]])
print(arr3+arr4)
print(np.add(arr3,arr4))

[[ 70  90]
 [110 130]]
[[ 70  90]
 [110 130]]


In [74]:
arr5 = np.array([[60,70],[80,90]])
arr6 = np.array([[10,20],[30,40]])
print(arr3-arr4)
print(np.subtract(arr3,arr4))

[[50 50]
 [50 50]]
[[50 50]
 [50 50]]


In [76]:
arr7 = np.array([[60,70],[80,90]])
arr8 = np.array([[10,20],[30,40]])
print(arr7*arr8)
print(np.multiply(arr7,arr8))

[[ 600 1400]
 [2400 3600]]
[[ 600 1400]
 [2400 3600]]


In [78]:
arr9 = np.array([[60,70],[80,90]])
arr10 = np.array([[10,20],[30,40]])
print(arr9/arr10)
print(np.divide(arr9,arr10))

[[6.         3.5       ]
 [2.66666667 2.25      ]]
[[6.         3.5       ]
 [2.66666667 2.25      ]]


In [80]:
arr5 = np.array([[60,70],[80,90]])
arr6 = np.array([3])
print(np.power(arr5,arr6))

[[216000 343000]
 [512000 729000]]


In [86]:
arr5 = np.array([60,70,80,90,100])
print(np.sqrt(arr5))

[ 7.74596669  8.36660027  8.94427191  9.48683298 10.        ]


### join and split 

In [95]:
arr44= np.array([60,70,80])
arr45 = np.array([10,20,30])
print(np.concatenate([arr44,arr45]))

[60 70 80 10 20 30]


In [101]:
arr9 = np.array([[60,70],[80,90]])
arr10 = np.array([[10,20],[30,40]])
print(np.concatenate([arr9,arr10], axis=1))

[[60 70 10 20]
 [80 90 30 40]]


In [103]:
arr9 = np.array([[60,70],[80,90]])
arr10 = np.array([[10,20],[30,40]])
print(np.concatenate([arr9,arr10], axis=0))

[[60 70]
 [80 90]
 [10 20]
 [30 40]]


In [107]:
print(np.hstack([arr9,arr10]))  # horizontal concatenation 

[[60 70 10 20]
 [80 90 30 40]]


In [111]:
print(np.vstack([arr9,arr10]))  # vertical concatenation 

[[60 70]
 [80 90]
 [10 20]
 [30 40]]


In [113]:
arr5 = np.array([60,70,80,90,100])
print(np.array_split(arr5,3))

[array([60, 70]), array([80, 90]), array([100])]


In [7]:
arr5 = np.array([60,70,80,90,100])
b = (np.array_split(arr5,3))
print(b[1]) # [array([60, 70]), array([80, 90]), array([100])] iska 1

[80 90]


In [13]:
arr5 = np.array([[60,70],[80,90],[100,110]])
b = (np.array_split(arr5,3))
print(b)

[array([[60, 70]]), array([[80, 90]]), array([[100, 110]])]


###  Adding and removing element in array

In [35]:
c = np.array([[20,30],[60,70]])
print(np.append(c,[40,50]))

[20 30 60 70 40 50]


In [29]:
a = np.array([20,30,60,70])
print(np.insert(a,2,[40,50])) # array , index, value

[20 30 40 50 60 70]


In [43]:
d = np.insert(c,1,[40,50],axis = 0)
print(d)

[[20 30]
 [40 50]
 [60 70]]


In [45]:
d = np.insert(c,1,[40,50],axis = 1)
print(d)

[[20 40 30]
 [60 50 70]]


In [53]:
print(np.insert(c,[1,2],[50],axis = 0))

[[20 30]
 [50 50]
 [60 70]
 [50 50]]


In [59]:
print(c)

[[20 30]
 [60 70]]


In [61]:
print(np.delete(c,1))

[20 60 70]


In [67]:
print(np.delete(c,1,axis = 1))

[[20]
 [60]]


In [69]:
print(np.delete(c,1,axis = 0))

[[20 30]]


### sort , filter and search

In [72]:
arr = np.array([7,5,6,8,2,4])
print(np.sort(arr))

[2 4 5 6 7 8]


In [80]:
arr = np.array([[7,5,6,8,2,4],[4,5,7,3,2,1]])
print(np.sort(arr))

[[2 4 5 6 7 8]
 [1 2 3 4 5 7]]


In [82]:
arr2 = np.array([3,4,1,7,8])
s= np.where(arr2 == 4)
print(s)

(array([1], dtype=int64),)


In [86]:
arr2 = np.array([3,4,1,7,8])
s= np.where(arr2%2==0)
print(s)  # search ke liye where use karna

(array([1, 4], dtype=int64),)


In [94]:
arr2 = np.array([1,2,3,4,5])
ss = np.searchsorted(arr2,5)  # use array element to search element index
print(ss)

4


In [96]:
a = np.array([20,30,40,50])
fa = [True, False, True , False]
new = a[fa]
print(new)

[20 40]


In [100]:
a = np.array([20,30,40,50])
fa = a>35
new = a[fa]
print(new)

[40 50]


In [104]:
a = np.array([20,30,40,50])
fa = a%2==0
new = a[fa]
print(new)

[20 30 40 50]


### Aggrecating numbers

In [114]:
a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [142]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price)
print(quantity)

print(np.sum(price))
print(np.min(price))
c = np.cumprod([price,quantity],axis = 0)
print(c[1].sum())

[100 150 199 200 250 130]
[10 50 30 40 30 10]
1029
100
31270


### Statistical functions in numpy

In [157]:
import numpy as np
import statistics as sts

backed_food = [200,300,150,130,200,280,170,188]

a = np.array(backed_food)
print(np.mean(a)) #sum of all value / number of values
print(np.median(a)) # biche middle 2 element + and % by 2 
print(sts.mode(a)) # most reoccur
print(np.std(a))
print(np.var(a))

202.25
194.0
200
55.68157235567257
3100.4375


In [149]:
print(np.sort(a))

[130 150 170 188 200 200 280 300]


In [161]:
#-1 represent inversly proporsional relationship
# 1 represent proporsional relationship
# 0 means no relationship
tobacco_consumption = [30,50,10,30,50,40]
death = [100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumption,death]))
    

[[1.         0.99015454]
 [0.99015454 1.        ]]
